### ISSUE TITLE
SmallTalk for bigger accounts

### ISSUE THREAD

**Issue by carlbordum** [ouchadam/small-talk#184] opened 2022-10-02 20:18 UTC
Hi there,

I'd love to try out SmallTalk.

My account is quite big, and so it takes forever to load (currently has been loading for over 50 hours).

If you are interested in this issue, please let me know how I can assist.

**Comment by ProjectMoon** [comment] 2022-10-03 19:09
You might actually be experiencing a bug where the sync response wasn't properly handled. Has been fixed but not yet released.

**Comment by ouchadam** [comment] 2022-10-04 18:14
thanks for raising an issue :100: this sounds like the above ^^^ 

a quick way to double check sync issues is to go into the in app settings (tapping your profile picture / first letter of your username in the bottom bar) then the top right gear icon, then _clear cache_ and then kill the app away (by swiping it away from the recents menu) and relaunch (I need to make this auto relaunch....)

if that doesn't help it could be there's a particular message type in your account that `SmallTalk` isn't able to handle yet and is silently crashing

**Comment by ouchadam** [comment] 2022-10-05 20:30
with a bit more testing I believe I've found the root cause, currently the app requires a _room creation event_ to exist in the first sync response for messages from said room 

it's possible for the creation events to not exist straight away if there's a _gappy sync_ or if a large number of other events have pushed the creation event to the next sync

**Comment by ouchadam** [comment] 2022-10-17 21:35
Looks like there was an intermittent bug during login which has been fixed by https://github.com/ouchadam/small-talk/pull/207

**Closed by ouchadam** 2022-10-17 21:35 UTC
